/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   Printftest.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: takwak <takwak@student.42gyeongsan.kr>     +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/10/10 20:13:50 by takwak            #+#    #+#             */
/*   Updated: 2024/10/31 03:26:01 by takwak           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"
#include <assert.h>

int	main(void)
{
	int	i;
	char	*p;
	int		ori_res;
	int		my_res;

	ft_printf("==========================\n");
	
	printf("\n%%s test\n");
	p = "Printftest chicken";
	printf("s != NULL\n");
	ori_res = printf("| printf return : %d\n", printf("%s", p));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%s", p));
	assert(ori_res != my_res);
	p = NULL;
	printf("s != NULL\n");
	// printf("%s\n", p);
	ft_printf("| ft_printf return : %d\n", ft_printf("%s", p));
	ft_printf("==========================\n");
	ori_res = printf("| printf return : %d\n", printf(" %s ", "-"));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %s ", "-"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %s %s ", "", "-"));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %s %s ", "", "-"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %s %s ", "-", ""));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %s %s ", "-", ""));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %s %s %s %s %s", " - ", "", "4", "", "2"));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %s %s %s %s %s", " - ", "", "4", "", "2"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%23s", NULL));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%23s", NULL));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("%%p test\n");
	printf("p != NULL\n");
	ori_res = printf("| printf return : %d\n", printf("%p", "1234"));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%p", "1234"));
	assert(ori_res != my_res);
	p = NULL;
	printf("p != NULL\n");
	ori_res = printf("| printf return : %d\n", printf("%p", p));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%p", p));
	assert(ori_res != my_res);
	ft_printf("| ft_printf return : %d\n", ft_printf(" %p %p ", 0, 0));
	ft_printf("==========================\n");
	
	printf("\n%%d test\n");
	printf("n != 2147483648\n");
	ori_res = printf("| printf return : %d\n", printf("%d", (int)2147483648));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%d", (int)2147483648));
	assert(ori_res != my_res);
	printf("n != -2147483648\n");
	ori_res = printf("| printf return : %d\n", printf("%d", (int)-2147483648));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%d", (int)-2147483648));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%d", -100));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%d", -100));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%d", -1));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%d", -1));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%d", (int)-2147483648));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%d", (int)-2147483648));
	assert(ori_res != my_res);
	ft_printf("| ft_printf return : %d\n", ft_printf("%d", (int)-1));
	ft_printf("==========================\n");

	printf("\n%%u test\n");
	ori_res = printf("| printf return : %d\n", printf("%u", 0));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%u", 0));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%u", -1));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%u", -1));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("\n%%x test\n");
	ori_res = printf("| printf return : %d\n", printf("%x", 0));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%x", 0));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%x", -1));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%x", -1));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("\n%%X test\n");
	ori_res = printf("| printf return : %d\n", printf("%X", 0));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%X", 0));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%X", -1));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%X", -1));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("\n%%%% test\n");
	ori_res = printf("| printf return : %d\n", printf("%%"));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%%"));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("\nbonus(- flag) test\n");
	printf("type c : ");
	ori_res = printf("| printf return : %d\n", printf("%-20c", 'c'));
	ft_printf("type c : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-20c", 'c'));
	assert(ori_res != my_res);
	printf("type s : ");
	ori_res = printf("| printf return : %d\n", printf("%-20s", "s format"));
	ft_printf("type s : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-20s", "s format"));
	assert(ori_res != my_res);
	printf("type p : ");
	ori_res = printf("| printf return : %d\n", printf("%-20p", "s format"));
	ft_printf("type p : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-20p", "s format"));
	assert(ori_res != my_res);
	printf("type d : ");
	ori_res = printf("| printf return : %d\n", printf("%-20d", 42));
	ft_printf("type d : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-20d", 42));
	assert(ori_res != my_res);
	printf("type i : ");
	ori_res = printf("| printf return : %d\n", printf("%-20i", 42));
	ft_printf("type i : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-20i", 42));
	assert(ori_res != my_res);
	printf("type u : ");
	ori_res = printf("| printf return : %d\n", printf("%-20u", 42));
	ft_printf("type u : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-20u", 42));
	assert(ori_res != my_res);
	printf("type x : ");
	ori_res = printf("| printf return : %d\n", printf("%-20x", 0x42));
	ft_printf("type x : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-20x", 0x42));
	assert(ori_res != my_res);
	printf("type X : ");
	ori_res = printf("| printf return : %d\n", printf("%-20X", 0x42));
	ft_printf("type X : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-20X", 0x42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%-10d", 12345));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-10d", 12345));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %-11p %-12p ", INT_MIN, INT_MAX));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %-11p %-12p ", INT_MIN, INT_MAX));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %-13p %-14p ", ULONG_MAX, -ULONG_MAX));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %-13p %-14p ", ULONG_MAX, -ULONG_MAX));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %-2p ", 1));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %-2p ", 1));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %-2p ", 15));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %-2p ", 15));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %-3p ", 16));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %-3p ", 16));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %-1d ", -0));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %-1d ", -0));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %-1d ", -9));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %-1d ", -9));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("\nbonus(+ flag) test\n");
	printf("type d : ");
	ori_res = printf("| printf return : %d\n", printf("%+20d", 42));
	ft_printf("type d : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%+20d", 42));
	assert(ori_res != my_res);
	printf("type i : ");
	ori_res = printf("| printf return : %d\n", printf("%+20i", 42));
	ft_printf("type i : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%+20i", 42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%+10d", 12345));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%+10d", 12345));
	assert(ori_res != my_res);
	ft_printf("==========================\n");
	
	printf("type d : ");
	ori_res = printf("| printf return : %d\n", printf("%+20d", -42));
	ft_printf("type d : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%+20d", -42));
	assert(ori_res != my_res);
	printf("type i : ");
	ori_res = printf("| printf return : %d\n", printf("%+20i", -42));
	ft_printf("type i : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%+20i", -42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%+10d", 12345));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%+10d", 12345));
	assert(ori_res != my_res);
	printf("type d : ");
	ori_res = printf("| printf return : %d\n", printf("%+d", -1));
	ft_printf("type d : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%+d", -1));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("\nbonus(' ' flag) test\n");
	ft_printf("==========================\n");
	printf("type d : ");
	ori_res = printf("| printf return : %d\n", printf("% d", 42));
	ft_printf("type d : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("% d", 42));
	assert(ori_res != my_res);
	printf("type i : ");
	ori_res = printf("| printf return : %d\n", printf("% i", 42));
	ft_printf("type i : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("% i", 42));
	assert(ori_res != my_res);
	printf("type d : ");
	ori_res = printf("| printf return : %d\n", printf("% d", -42));
	ft_printf("type d : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("% d", -42));
	assert(ori_res != my_res);
	printf("type i : ");
	ori_res = printf("| printf return : %d\n", printf("% i", -42));
	ft_printf("type i : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("% i", -42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("% d", 12345));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("% d", 12345));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("% d", -12345));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("% d", -12345));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%-10d", 12345));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%-10d", 12345));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("\nbonus(# flag) test\n");
	printf("type x : ");
	ori_res = printf("| printf return : %d\n", printf("%#x", 0x42));
	ft_printf("type x : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%#x", 0x42));
	assert(ori_res != my_res);
	printf("type X : ");
	ori_res = printf("| printf return : %d\n", printf("%#X", 0x42));
	ft_printf("type X : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%#X", 0x42));
	assert(ori_res != my_res);
	printf("type X : ");
	ori_res = printf("| printf return : %d\n", printf("%#X", 0));
	ft_printf("type X : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%#X", 0));
	assert(ori_res != my_res);
	printf("type X : ");
	ori_res = printf("| printf return : %d\n", printf("%#X", LONG_MIN));
	ft_printf("type X : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%#X", LONG_MIN));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("\nbonus(0 flag) test\n");
	ft_printf("type d : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010d", 42));
	printf("type d : ");
	ori_res = printf("| printf return : %d\n", printf("%010d", 42));
	assert(ori_res != my_res);
	ft_printf("type i : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010i", 42));
	printf("type i : ");
	ori_res = printf("| printf return : %d\n", printf("%010i", 42));
	assert(ori_res != my_res);
	ft_printf("type u : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010u", 42));
	printf("type u : ");
	ori_res = printf("| printf return : %d\n", printf("%010u", 42));
	assert(ori_res != my_res);
	ft_printf("type x : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010x", 0x42));
	printf("type x : ");
	ori_res = printf("| printf return : %d\n", printf("%010x", 0x42));
	assert(ori_res != my_res);
	ft_printf("type X : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010X", 0x42));
	printf("type X : ");
	ori_res = printf("| printf return : %d\n", printf("%010X", 0x42));
	assert(ori_res != my_res);
	printf("type d : ");
	ori_res = printf("| printf return : %d\n", printf("%010d", -42));
	ft_printf("type d : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010d", -42));
	assert(ori_res != my_res);
	printf("type i : ");
	ori_res = printf("| printf return : %d\n", printf("%010i", -42));
	ft_printf("type i : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010i", -42));
	assert(ori_res != my_res);
	printf("type u : ");
	ori_res = printf("| printf return : %d\n", printf("%010u", 42));
	ft_printf("type u : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010u", 42));
	assert(ori_res != my_res);
	printf("type x : ");
	ori_res = printf("| printf return : %d\n", printf("%010x", 0x42));
	ft_printf("type x : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010x", 0x42));
	assert(ori_res != my_res);
	printf("type X : ");
	ori_res = printf("| printf return : %d\n", printf("%010X", 0x42));
	ft_printf("type X : ");
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010X", 0x42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %01d ", 0));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %01d ", 0));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %012d ", LONG_MIN));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf(" %012d ", LONG_MIN));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%08.3i", 8375));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%08.3i", 8375));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	printf("\nbonus(number width) test\n");
	ori_res = printf("| printf return : %d\n", printf("%010d", 12345));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%010d", 12345));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%03d", 12345));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%03d", 12345));
	assert(ori_res != my_res);
	ft_printf("==========================\n");

	// printf("\nbonus(* width) test\n");
	// printf("| printf return : %d\n", printf("%0*d", 10, 12345));
	// ft_printf("| ft_printf return : %d\n", ft_printf("%0*d", 10, 12345));
	// printf("| printf return : %d\n", printf("%010d", 12345));
	// ft_printf("| ft_printf return : %d\n", ft_printf("%010d", 12345));
	// ft_printf("| ft_printf return : %d\n", ft_printf("%-10d", 12345));
	// ft_printf("==========================\n");
  
	printf("\nbonus(. prec) test\n");
	ori_res = printf("| printf return : %d\n", printf("%10.1s", "42"));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%10.1s", "42"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%10.3d", -42));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%10.3d", -42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3i", 42));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.3i", 42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3u", 42));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.3u", 42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3x", 42));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.3x", 42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3X", 42));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.3X", 42));
	assert(ori_res != my_res);
	ft_printf("==========================\n");
	ori_res = printf("| printf return : %d\n", printf("%11.10s", "424242"));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%11.10s", "424242"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3d", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.3d", 424242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%+10.3i", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%+10.3i", 424242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3u", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.3u", 424242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3x", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.3x", 424242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3X", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.3X", 424242));
	assert(ori_res != my_res);
	ft_printf("==========================\n");
	ori_res = printf("| printf return : %d\n", printf("%.s", "424242"));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.s", "424242"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%+3.10d", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%+3.10d", 424242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%3.10i", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%3.10i", 424242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%3.10u", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%3.10u", 424242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%#11.10x", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%#11.10x", 424242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.X", 424242));
	my_res = ft_printf("| ft_printf return : %d\n", ft_printf("%.X", 424242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.s", NULL));
	my_res = ft_printf("| ft_printf return : %d\n\n\n", ft_printf("%.s", NULL));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%3.1s", NULL));
	my_res = ft_printf("| ft_printf return : %d\n\n\n", ft_printf("%3.1s", NULL));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3s", NULL));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%.3s", NULL));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%10.s", NULL));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%10.s", NULL));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%-7.5s", "tubular"));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%-7.5s", "tubular"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%-10.8s", NULL));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%-10.8s", NULL));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.09s", NULL));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%.09s", NULL));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.0i", 0));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%.0i", 0));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%5.0i", 0));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%5.0i", 0));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.0i", 10));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%.0i", 10));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.0u", 0));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%.0u", 0));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%5.0u", 0));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%5.0u", 0));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%15p", NULL));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%15p", NULL));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%--120.50d" , -1355834522));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%--120.50d", -1355834522));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%-%%-112.167X" , 3814946551u));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%-%%-112.167X" , 3814946551u));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%-32.65u" , 404243169u));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%-32.65u" , 404243169u));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%-#120.50d" , -1355834522));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%-#120.50d", -1355834522));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%-00120.50d" , -1355834522));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%-00120.50d", -1355834522));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%197c%12p%013.i%--147.185x%-1c" ,7,(void*)18229185041105221837lu,-1488496170,703835510u,120));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%197c%12p%013.i%--147.185x%-1c" ,7,(void*)18229185041105221837lu,-1488496170,703835510u,120));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%013.i" , -1488496170));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%013.i" , -1488496170));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%08.5i" , 42));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%08.5i" , 42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf(" %.6i ", -9));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf(" %.6i ", -9));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%7.5s", "yolo"));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%7.5s", "yolo"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%-0007.5s", "yolo"));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%-7.4s", "yolo"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%0+-6d", -42));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%0+-6d", -42));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%13.10d", -4242));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%13.10d", -4242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%13.10d", -4242));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%13.10d", -4242));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%.3p", NULL));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("%.3p", NULL));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%y"));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("(%z)", "123"));
	assert(ori_res != my_res);
	ori_res = printf("| printf return : %d\n", printf("%x", 123));
	my_res = ft_printf("| ft_printf return : %d\n\n", ft_printf("(%x)", 123));
	assert(ori_res != my_res);
	ft_printf("==========================\n");
}
